import type { Metadata } from "next";
import "./globals.css";
import NavigationComponent from "@/aymericdev/app/components/navigation.component";
import {ReactNode} from "react";
import FooterComponent from "@/aymericdev/app/components/footer.component";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <div className="adev-body-block">
          <NavigationComponent />

          {children}

          <FooterComponent />
        </div>
      </body>
    </html>
  );
}
